pipeline {
    agent any
    options {
        skipDefaultCheckout true
    }

    stages {
        stage('Clone Repository') {
             steps {
                git 'https://github.com/KavinduJayathilaka/HolidayHomes-MEAN_Stack-V2.git'
               credentialsId  '9f10d6fd-0427-4aab-b612-a913fd91854a'
            }
        }

        stage('Build') {
            steps {
                sh './gradlew build'
            }
        }

        stage('Test') {
            steps {
                sh './gradlew test'
            }
        }

        stage('Deploy') {
            steps {
                sh './deploy.sh'
            }
        }
    }

    post {
        always {
            githubStatus context: 'continuous-integration/jenkins', state: 'success'
          
                githubComment message: "The pipeline completed successfully!"
                githubLabel labels: ['approved']
    
        }
    }
}
