pipeline {
    agent any
    options {
        skipDefaultCheckout true
    }

    stages {
        stage('Clone Repository') {
             steps {
                git 'https://github.com/KavinduJayathilaka/HolidayHomes-MEAN_Stack-V2.git'
               credentialsId : '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'
            }
        }

        stage('Build') {
            steps {
                sh './gradlew build'
            }
        }

        stage('Test') {
            steps {
                sh './gradlew test'
            }
        }

        stage('Deploy') {
            steps {
                sh './deploy.sh'
            }
        }
    }

    post {
        always {
            githubStatus context: 'continuous-integration/jenkins', state: 'success'
          
                githubComment message: "The pipeline completed successfully!"
                githubLabel labels: ['approved']
    
        }
    }
}
